version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      #- restore_cache:
       #   key: ~/project/Pathfinder/ClientApp-{{ .Branch }}-{{ checksum "package-lock.json" }}
      #- run: npm install
    # - save_cache:
        #  key: ~/project/Pathfinder/ClientApp-{{ .Branch }}-{{ checksum "package-lock.json" }}
       #   paths:
       #   - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI