version: 2
jobs:
  build:
    working_directory: ~/pathfinder2e/Pathfinder/ClientApp
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      #- restore_cache:
          #key: ~/Pathfinder/ClientApp-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      #- save_cache:
         # key: repo-{{ .Branch }}-{{ checksum "package-lock.json" }}
         # paths:
         #  - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI