version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:14-browsers
        environment:
          CHROME_BIN: /usr/bin/google-chrome
    steps:
      - checkout
      - restore_cache: 
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm --prefix ./Pathfinder/ClientApp install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm --prefix ./Pathfinder/ClientApp run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
