version: 2
jobs:
  build:
    working_directory: ~/pathfinder2e/Pathfinder/ClientApp
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
